<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		
		<title>{% block title %}{% endblock %}</title>
		
		<link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/vendor/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="/vendor/jquery-ui-custom/jquery-ui.min.css">
		<link rel="stylesheet" type="text/css" href="/vendor/sb-admin/css/sb-admin.min.css">
		<link rel="stylesheet" type="text/css" href="/css/common.css">
{% block extrastyle %}{% endblock %}
	</head>
	<body class="fixed-nav sticky-footer bg-dark" id="page-top">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
			<a class="navbar-brand" href="/">DIRT</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expand="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav navbar-sidenav" id="topAccordion">
					<li class="nav-item" title="Dashboard">
						<a class="nav-link" href="/dashboard">
							<i class="fa fa-dashboard fa-fw"></i>
							<span class="nav-link-text">Dashboard</span>
						</a>
					</li>
					<li class="nav-item" title="My Lists">
						<a class="nav-link" href="/my-lists">
							<i class="fa fa-list fa-fw"></i>
							<span class="nav-link-text">My Lists</span>
						</a>
					</li>
					<li class="nav-item" title="Market Browser">
						<a class="nav-link" href="/browse">
							<i class="fa fa-bar-chart-o fa-fw"></i>
							<span class="nav-link-text">Market Browser</span>
						</a>
					</li>
					<li class="nav-item" title="Station Trading">
						<a class="nav-link" href="/station-trade">
							<i class="fa fa-exchange fa-rotate-90 fa-fw"></i>
							<span class="nav-link-text">Station Trading</span>
						</a>
					</li>
					<li class="nav-item" title="Import Analysis">
						<a class="nav-link" href="/import">
							<i class="fa fa-sign-in fa-fw"></i>
							<span class="nav-link-text">Import Analysis</span>
						</a>
					</li>
					<li class="nav-item" title="Export Analysis">
						<a class="nav-link" href="/export">
							<i class="fa fa-sign-out fa-fw"></i>
							<span class="nav-link-text">Export Analysis</span>
						</a>
					</li>
					<li class="nav-item" title="Economic Reports">
						<a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseReports" data-parent="#topAccordion">
							<i class="fa fa-line-chart fa-fw"></i>
							<span class="nav-link-text">Economic Reports</span>
						</a>
						<ul class="sidenav-second-level collapse" id="collapseReports">
							<li>
								<a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseRegional">Regional Statistics</a>
								<ul class="sidenav-third-level collapse" id="collapseRegional">
									<li>
										<a href="/economic-reports/regional-by-region">By Region</a>
									</li>
									<li>
										<a href="/economic-reports/regional-by-statistic">By Statistic</a>
									</li>
									<li>
										<a href="/economic-reports/regional-by-month">By Month</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="/economic-reports/mined-produced-destroyed">Mined, Produced, Destroyed</a>
							</li>
							<li>
								<a href="/economic-reports/velocity-of-isk">Velocity of Isk</a>
							</li>
							<li>
								<a href="/economic-reports/money-supply">Money Supply</a>
							</li>
							<li>
								<a href="/economic-reports/isk-faucets-sinks">Isk Faucets &amp; Sinks</a>
							</li>
						</ul>
					</li>
					<li class="nav-item" title="Kill Dump">
						<a class="nav-link" href="/kill-dump">
							<i class="fa fa-paper-plane-o fa-fw"></i>
							<span class="nav-link-text">Kill Dump</span>
						</a>
					</li>
					<li class="nav-item" title="Fortizar Chain">
						<a class="nav-link" href="/fortizar-chain">
							<i class="fa fa-share-alt fa-fw"></i>
							<span class="nav-link-text">Fortizar Chain</span>
						</a>
					</li>
				</ul>
				<ul class="navbar-nav sidenav-toggler">
					<li class="nav-item">
						<a class="nav-link text-center" id="sidenavToggler">
							<i class="fa fa-angle-left fa-fw"></i>
						</a>
					</li>
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<form class="form-inline my-2 my-lg-0 mr-lg-2" action="/search" method="get">
							<div class="input-group">
								<input class="form-control autocomplete" type="text" id="search" name="q" placeholder="Search for item...">
								<span class="input-group-append">
									<button class="btn btn-primary" type="submit">
										<i class="fa fa-search"></i>
									</button>
								</span>
							</div>
						</form>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle ml-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-gear fa-fw"></i>
							<span class="d-lg-none">Settings</span>
							<span class="indicator text-warning d-none d-lg-block">
								<i class="fa fa-fw fa-cicle"></i>
							</span>
						</a>
						<div class="dropdown-menu" aria-labelledby="alertsDropdown">
							<a class="dropdown-item" href="/user-settings">
								<span class="text-success">
									<strong><i class="fa fa-gear fa-fw"></i>User</strong>
								</span>
							</a>
							{% if admin %}
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="/admin">
								<span class="text-danger">
									<strong><i class="fa fa-gear fa-fw"></i>Admin</strong>
								</span>
							</a>
							{% endif %}
						</div>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/logout">
							<i class="fa fa-fw fa-sign-out"></i>Logout
						</a>
					</li>
				</ul>
			</div>
		</nav>
		<div class="content-wrapper">
			<div class="container-fluid">
{% block content %}{% endblock %}
			</div>
			<footer class="sticky-footer">
				<div class="container">
					<div class="text-center">
						<small>&copy;2019 Austin Selick-Bottos, EVE Online and the EVE logo are the registered trademarks of CCP hf.</small>
					</div>
				</div>
			</footer>
		</div>
		<script type="text/javascript" src="/vendor/jquery/jquery.min.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
		<script type="text/javascript" src="/vendor/jquery-easing/jquery.easing.min.js"></script>
		<script type="text/javascript" src="/vendor/jquery-ui-custom/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/vendor/sb-admin/js/sb-admin.min.js"></script>
		<script type="text/javascript" src="/js/common.js"></script>
{% block extrahead %}{% endblock %}
{% block extrascript %}{% endblock %}
	</body>
</html>
