{% extends "base.phtml" %}
{% block title %}Market Browser{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
{% include 'chart-libs.phtml' %}
<script type="text/javascript" src="js/browser-menu.js"></script>
<script type="text/javascript" src="js/market-browser.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><img id="title-img"> <span id="title">Market Browser</span></h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text">Region</span>
			</div>
			<select class="form-control" id="regionselect">
				<option value="0">All Regions</option>
				<optgroup label="TEST">
					<option value="10000039">Esoteria</option>
					<option value="10000059">Paragon Soul</option>
				</optgroup>
				<optgroup label="Legacy">
					<option value="10000014">Catch</option>
					<option value="10000025">Immensea</option>
					<option value="10000061">Tenerifis</option>
					<option value="10000031">Impass</option>
					<option value="10000056">Feythabolis</option>
					<option value="10000062">Omist</option>
					<option value="10000022">Stain</option>
				</optgroup>
				<optgroup label="Hubs">
					<option value="10000002">The Forge (Jita)</option>
					<option value="10000043">Domain (Amarr)</option>
					<option value="10000032">Sinq Liasion (Dodixie)</option>
					<option value="10000030">Heimatar (Rens)</option>
				</optgroup>
			</select>
		</div>
	</div>
	<div class="col-md-4">
	</div>
	<div class="col-md-1">
	</div>
	<div class="col-md-3 no-padding-left">
		<div class="btn-group mb-3">
			<button type="button" class="btn btn-primary active" id="open-in-market-browser"><i class="fa fa-bar-chart-o fa-fw"></i></button>
			<button type="button" class="btn btn-primary" id="open-in-station-trader"><i class="fa fa-exchange fa-rotate-90 fa-fw"></i></button>
			<button type="button" class="btn btn-primary" id="open-in-import-analyzer"><i class="fa fa-sign-in fa-fw"></i></button>
		</div>
		<div class="btn-group mb-3">
			<button type="button" class="btn btn-primary" id="oig"><i class="fa fa-magnet fa-fw"></i></button>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="selltablabel" href="#sell" data-toggle="tab" role="tab" aria-controls="sell" aria-selected="true"><i class="fa fa-long-arrow-up fa-fw"></i> Sell</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="buytablabel" href="#buy" data-toggle="tab" role="tab" aria-controls="buy" aria-selected="false"><i class="fa fa-long-arrow-down fa-fw"></i> Buy</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="depthtablabel" href="#depth" data-toggle="tab" role="tab" aria-controls="depth" aria-selected="false"><i class="fa fa-align-center fa-fw"></i> Depth</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="histtablabel" href="#history" data-toggle="tab" role="tab" aria-controls="history" aria-selected="false"><i class="fa fa-history fa-fw"></i> History</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border mb-3 show active" id="sell" aria-labelledby="selltablabel">
						<div class="table-responsive">
							<table id="sellorders" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="buy" aria-labelledby="buytablabel">
						<div class="table-responsive">
							<table id="buyorders" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="depth" aria-labelledby="depthtablabel">
						<div class="card no-border mt-3 mb-3">
							<div class="card-body chart-card-body" style="position:relative; max-height:600px">
								<canvas id="orderdepth"></canvas>
							</div>
						</div>
						<div class="card chart-card mb-3">
							<div class="card-body chart-card-body">
							</div>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="history" aria-labelledby="historytablabel">
						<div class="btn-group" role="group">
							<button type="button" class="btn btn-primary" id="dates-all">All</button>
							<button type="button" class="btn btn-primary" id="dates-1y">1y</button>
							<button type="button" class="btn btn-primary" id="dates-6m">6m</button>
							<button type="button" class="btn btn-primary" id="dates-3m">3m</button>
							<button type="button" class="btn btn-primary" id="dates-1m">1m</button>
						</div>
						<div class="card mb-3 no-border">
							<div class="card-body chart-card-body" style="position:relative; max-height:600px">
								<canvas id="itemhistory"></canvas>
							</div>
						</div>
						<div class="card chart-card mb-3">
							<div class="card-header chart-card-header">
								<a data-toggle="collapse" href="#collapseOne" aria-expanded="false" class="collapsed">Raw Data</a>
							</div>
							<div id="collapseOne" class="card-body chart-card-body collapse" aria-expanded="false">
								<div class="table-responsive">
									<table id="rawhistory" class="table responsive table-striped table-condensed" style="width:100%"></table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 no-padding-left">
		<div class="panel panel-default browse-panel mb-3">
			<div class="accordian" id="g0b"></div>
		</div>
	</div>
</div>
{% endblock %}
