<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>

<script src="https://code.highcharts.com/stock/7.1/highstock.js"></script>
<script src="https://code.highcharts.com/stock/7.1/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/7.1/modules/export-data.js"></script>

<!--<script type="text/javascript" src="/js/chart-theme.js"></script>-->

