{% extends "base.phtml" %}
{% block title %}Alliance Contracts{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/contracts.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-handshake-o fa-fw"></i> Alliance Contracts</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		Exchange <button onclick="loadExchangeContracts()">Outstanding</button><button onclick="loadFinishedExchangeContracts()">Finished</button><br />
		Courier <button onclick="loadCourierContracts()">Outstanding</button><button onclick="loadInProgressCourierContracts()">In Progress</button><button onclick="loadFinishedCourierContracts()">Finished</button><button onclick="loadFailedCourierContracts()">Failed</button><br />
		Auction <button onclick="loadOpenAuctionContracts()">Outstanding</button><button onclick="loadFinishedAuctionContracts()">Finished</button><br />
	</div>
	<div class="col-sm-6">
		Capitals <button onclick="loadOpenCapContracts()">Outstanding</button><button onclick="loadFinishedCapContracts()">Finished</button><br />
		Corp Business <button onclick="loadOpenCorpLogiContracts()">Outstanding</button><button onclick="loadFinishedCorpLogiContracts()">Finished</button><br />
		Competition <button onclick="loadBigContractors()">Big Contractors</button><br />
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<hr />
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<div class="table-responsive">
					<table id="contracts-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
