{% extends "base.phtml" %}
{% block title %}Contract{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/contract.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-handshake-o fa-fw"></i> Contract</h3><a id="open-in-game" class="open-in-game-contract" data-contractid="" href="#"><i class="fa fa-magnet fa-fw"></i></a>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<div class="table-responsive">
					<table id="contract-items-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 no-padding-left">
	</div>
</div>
{% endblock %}
