{% extends "base.phtml" %}
{% block title %}Contract{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
    $('#offertable').DataTable({
        order: [[0, "asc"]],
        paging: true,
        pageLength: 25,
        bInfo: false,
        responsive: true,
        select: true
    });
    $('#asktable').DataTable({
        order: [[0, "asc"]],
        paging: true,
        pageLength: 25,
        bInfo: false,
        responsive: true,
        select: true
    });
} );
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-handshake-o fa-fw"></i> Contract {{contractid}} <a id="open-in-game" class="open-in-game-contract" data-contractid="{{contractid}}" href="#"><i class="fa fa-magnet fa-fw"></i></a></h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<p>Issuer: {{cinfo.issuer}}</p>
		<p>Location: {{cinfo.locationName}}</p>
		<p>Availability: {{cinfo.availability}}</p>
{% if cinfo.assignee %}
		<p>Assignee: {{cinfo.assignee}}</p>
{% endif %}
	</div>
	<div class="col-sm-6">
		<p>Status: {{cinfo.status}}</p>
		<p>Description: {{cinfo.title}}</p>
		<p>Issued: {{cinfo.dateIssued}}</p>
{% if cinfo.dateCompleted %}
		<p>Completed: {{cinfo.dateCompleted}}</p>
{% endif %}
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<p>Acceptor Will Pay: {{cinfo.price|number_format(0)}} isk</p>
		<p>Acceptor Will Receive: {{cinfo.reward|number_format(0)}} isk</p>
	</div>
</div>
{% if offeritems %}
<div class="row">
	<div class="col-md-12">
		<hr><h5>Offered</h5>
		<div class="table-responsive">
			<table id="offertable" class="table responsive table-striped table-condensed">
				<thead>
					<tr>
						<th>Type</th>
						<th>Qt</th>
					</tr>
				</thead>
				<tbody>
{% for item in offeritems %}
					<tr>
						<td>{{item.typeName}}</td>
						<td>{{item.quantity}}</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endif %}
{% if askitems %}
<div class="row">
	<div class="col-md-12">
		<hr><h5>Asking For</h5>
		<div class="table-responsive">
			<table id="asktable" class="table responsive table-striped table-condensed">
				<thead>
					<tr>
						<th>Type</th>
						<th>Qt</th>
					</tr>
				</thead>
				<tbody>
{% for item in askitems %}
					<tr>
						<td>{{item.typeName}}</td>
						<td>{{item.quantity}}</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endif %}
{% endblock %}
