{% extends "base.phtml" %}
{% block title %}Export Analyzer{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/browser-menu.js"></script>
<script type="text/javascript" src="js/export-analyzer.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-sign-out fa-fw"></i> Export Opportunities</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="s2jb-label" href="#s2jb" data-toggle="tab" role="tab" aria-controls="s2jb" aria-selected="true"><i class="fa fa-flag fa-fw"></i>Staging<i class="fa fa-angle-right fa-fw"></i>JBV</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="s2js-label" href="#s2js" data-toggle="tab" role="tab" aria-controls="s2js" aria-selected="false"><i class="fa fa-flag fa-fw"></i>Staging<i class="fa fa-angle-right fa-fw"></i>JSV</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="h2jb-label" href="#h2jb" data-toggle="tab" role="tab" aria-controls="h2jb" aria-selected="false"><i class="fa fa-home fa-fw"></i>Home<i class="fa fa-angle-right fa-fw"></i>JBV</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="h2js-label" href="#h2js" data-toggle="tab" role="tab" aria-controls="h2js" aria-selected="false"><i class="fa fa-home fa-fw"></i>Home<i class="fa fa-angle-right fa-fw"></i>JSV</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border show active" id="s2jb" aria-labelledby="s2jb-label">
						<div class="table-responsive mb-3">
							<table id="ss2jb" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="s2js" aria-labelledby="s2js-label">
						<div class="table-responsive mb-3">
							<table id="ss2js" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="h2jb" aria-labelledby="h2jb-label">
						<div class="table-responsive mb-3">
							<table id="hs2jb" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="h2js" aria-labelledby="h2js-label">
						<div class="table-responsive mb-3">
							<table id="hs2js" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 no-padding-left">
		<div class="card">
			<div class="card-header">
				<a>Freight</a>
			</div>
			<div class="card-body">
			</div>
		</div>
		<div class="card mt-3">
			<div class="card-header">
				<a>Filters</a>
			</div>
			<div class="card-body">
				<div class="input-group">
					<div class="input-group-prepend">
						<div class="input-group-text">&#x01B5; Profit &gt;</div>
					</div>
					<input type="text" class="form-control" placeholder="isk">
				</div>
				<div class="input-group">
					<div class="input-group-prepend">
						<div class="input-group-text">&percnt; Profit &gt;</div>
					</div>
					<input type="text" class="form-control" placeholder="&percnt;">
				</div>
				<div class="btn-group">
					<button type="button" class="btn btn-primary">Filter</button>
					<button type="button" class="btn btn-primary">Clear</button>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
