{% extends "base.phtml" %}
{% block title %}Export Analyzer{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/browser-menu.js"></script>
<script type="text/javascript" src="js/export-analyzer.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-sign-out fa-fw"></i> Export Opportunities</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="stagingtojitalabel" href="#stagingtojita" data-toggle="tab" role="tab" aria-controls="stagingtojita" aria-selected="true"><i class="fa fa-flag fa-fw"></i> Staging</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="hometojitalabel" href="#hometojita" data-toggle="tab" role="tab" aria-controls="hometojita" aria-selected="false"><i class="fa fa-home fa-fw"></i> Home</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border show active" id="stagingtojita" aria-labelledby="stagingtojitalabel">
						<div class="table-responsive">
							<table id="ss2jb" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
							<table id="ss2js" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="hometojita" aria-labelledby="hometojitalabel">
						<div class="table-responsive">
							<table id="hs2jb" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
							<table id="hs2js" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 no-padding-left">
		<div class="panel panel-default browse-panel">
			<div class="accordian" id="g0b"></div>
		</div>
	</div>
</div>
{% endblock %}
