{% extends "base.phtml" %}
{% block title %}Notifications{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" id="title">Notifications</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<form action="/notifications" method="post">
			<input type="hidden" id="notifId" name="notifId" value="all">
			<button type="submit" class="btn btn-primary">Acknowledge All</button>
		</form>
		<br />
		<div class="table-responsive">
			<table class="table responsive table-striped table-condensed">
{% for result in notiflist %}
				<tr>
					<td>{{result.time}}</td>
					<td>{{result.text}}</td>
					<td>
{% if result.acknowledged == 0 %}
						<form action="/notifications" method="post">
							<input type="hidden" id="notifId" name="notifId" value="{{result.notifId}}">
							<button type="submit" class="btn btn-primary">Acknowledge</button>
						</form>
{% endif %}
					</td>
				</tr>
{% endfor %}
			</table>
		</div>
	</div>
	<div class="col-md-3">
	</div>
	<div class="col-md-3">
	</div>
</div>
{% endblock %}
