<option value="0">All Regions</option>
<optgroup label="TEST">
	<option value="10000005">Detorid</option>
	<option value="10000039">Esoteria</option>
	<option value="10000059">Paragon Soul</option>
	<option value="10000056">Feythabolis</option>
</optgroup>
<optgroup label="Legacy">
	<option value="10000014">Catch</option>
	<option value="10000025">Immensea</option>
	<option value="10000031">Impass</option>
	<option value="10000061">Tenerifis</option>
	<option value="10000062">Omist</option>
</optgroup>
<optgroup label="Hubs">
	<option value="10000002">The Forge (Jita)</option>
	<option value="10000043">Domain (Amarr)</option>
	<option value="10000032">Sinq Liasion (Dodixie)</option>
	<option value="10000030">Heimatar (Rens)</option>
</optgroup>