{% extends "base.phtml" %}
{% block title %}Wallet{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/wallet.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-9">
		<h3 class="page-header"><i class="fa fa-credit-card fa-fw"></i> Wallet</h3>
		<hr>
	</div>
	<div class="col-sm-3 no-padding-left">
		<div class="card mb-3">
			<div class="card-header">
			</div>
			<div class="card-body">
				<p>Balance</p>
			</div>
			<div class="card-footer">
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="sell-orders-label" href="#sell-orders" data-toggle="tab" role="tab" aria-controls="sell-orders" aria-selected="true"><i class="fa fa-align-center fa-fw"></i> Sell Orders</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="buy-orders-label" href="#buy-orders" data-toggle="tab" role="tab" aria-controls="buy-orders" aria-selected="false"><i class="fa fa-align-center fa-fw"></i> Buy Orders</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="transactions-label" href="#transactions" data-toggle="tab" role="tab" aria-controls="transactions" aria-selected="false"><i class="fa fa-long-arrow-up fa-fw"></i> Transactions</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="journal-label" href="#journal" data-toggle="tab" role="tab" aria-controls="journal" aria-selected="false"><i class="fa fa-long-arrow-down fa-fw"></i> Journal</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border mb-3 show active" id="sell-orders" aria-labelledby="sell-orders-label">
						<div class="table-responsive">
							<table id="sell-orders-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="buy-orders" aria-labelledby="buy-orders-label">
						<div class="table-responsive">
							<table id="buy-orders-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="transactions" aria-labelledby="transactions-label">
						<div class="table-responsive">
							<table id="transactions-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="journal" aria-labelledby="journal-label">
						<div class="table-responsive">
							<table id="journal-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 no-padding-left">
		<div class="card">
			<div class="card-header">
			</div>
			<div class="card-body">
				<table class="no-border">
					<tr>
						<td>Number of Orders</td>
						<td></td>
					</tr>
					<tr>
						<td>Sell Order Total</td>
						<td></td>
					</tr>
					<tr>
						<td>Buy Order Total</td>
						<td></td>
					</tr>
					<tr>
						<td>Escrow Total</td>
						<td></td>
					</tr>
				</table>
			</div>
			<div class="card-footer">
			</div>
		</div>
	</div>
</div>
{% endblock %}
