{% extends "base.phtml" %}
{% block title %}Mined, Produced, Destroyed{% endblock %}
{% block extrahead %}
{% include 'chart-libs.phtml' %}
<script type="text/javascript" src="/js/mined-produced-destroyed.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header">Mined, Produced, Destroyed</h3>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="btn-group" data-toggle="buttons">
			<label class="btn btn-primary" id="dates-all">
				<input type="radio" autocomplete="off">All
			</label>
			<label class="btn btn-primary" id="dates-3y">
				<input type="radio" autocomplete="off">3y
			</label>
			<label class="btn btn-primary" id="dates-1y">
				<input type="radio" autocomplete="off">1y
			</label>
			<label class="btn btn-primary active" id="dates-6m">
				<input type="radio" autocomplete="off" checked>6m
			</label>
			<label class="btn btn-primary" id="dates-3m">
				<input type="radio" autocomplete="off">3m
			</label>
			<label class="btn btn-primary" id="dates-1m">
				<input type="radio" autocomplete="off">1m
			</label>
		</div>
	</div>
</div>
<div class="row margin-top">
	<div class="card card-block">
		<canvas id="mined-produced-destroyed" width="100%" height="400px"></canvas>
	</div>
</div>
<div class="row">
	<div class="card card-block">
		<p></p>
	</div>
</div>
{% endblock %}
