{% extends "base.phtml" %}
{% block title %}Market Browser{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
{% include 'chart-libs.phtml' %}
<script type="text/javascript" src="js/browser-menu.js"></script>
<script type="text/javascript" src="js/market-browser.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" ><img id="title-img"> <span id="title">Market Browser</span> <a id="oig"><i class="fa fa-magnet fa-fw"></i></a></h3>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="form-group input-group">
			<span class="input-group-addon">Region</span>
			<select class="form-control" id="regionselect">
				<option value="0">All Regions</option>
				<!--<optgroup label="TEST">
					<option value="10000039">Esoteria</option>
					<option value="10000059">Paragon Soul</option>
					<option value="10000014">Catch</option>
					<option value="10000022">Stain</option>
				</optgroup>-->
				<optgroup label="Hubs">
					<option value="10000002">The Forge (Jita)</option>
					<option value="10000043">Domain (Amarr)</option>
					<option value="10000032">Sinq Liasion (Dodixie)</option>
					<option value="10000030">Heimatar (Rens)</option>
					<option value="10000042">Metropolis (Hek)</option>
				</optgroup>
			</select>
		</div>
	</div>
	<div class="col-md-4">
	</div>
	<div class="col-md-1">
	</div>
	<div class="col-md-3">
		<div class="btn-group margin-bottom">
			<button type="button" class="btn btn-primary active" id="open-in-market-browser"><i class="fa fa-bar-chart-o fa-fw"></i></button>
			<button type="button" class="btn btn-primary" id="open-in-import-analyzer"><i class="fa fa-truck fa-fw"></i></button>
			<button type="button" class="btn btn-primary" id="open-in-station-trader"><i class="fa fa-exchange fa-fw"></i></button>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs">
					<li class="active" id="selltablabel"><a href="#sell" data-toggle="tab"><i class="fa fa-long-arrow-up fa-fw"></i> Sell</a></li>
					<li id="buytablabel"><a href="#buy" data-toggle="tab"><i class="fa fa-long-arrow-down fa-fw"></i> Buy</a></li>
					<li id="depthtablabel"><a href="#depth" data-toggle="tab"><i class="fa fa-align-center fa-fw"></i> Depth</a></li>
					<li id="histtablabel"><a href="#history" data-toggle="tab"><i class="fa fa-history fa-fw"></i> History</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border in active" id="sell">
						<div class="table-responsive">
							<table id="sellorders" class="table responsive table-striped table-hover table-condensed" width="100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border" id="buy">
						<div class="table-responsive">
							<table id="buyorders" class="table responsive table-striped table-hover table-condensed" width="100%"></table>
						</div>
					</div>
					<div class="tab-pane fade" id="depth">
						<div class="well margin-top">
							<canvas id="orderdepth"></canvas>
						</div>
						<div class="well">
							<p>This a visual representation of the order book showing the cumulative volume of active buy &amp; sell orders at the different price points. The x axis ranges from -20% best buy to +20% best sell.</p>
						</div>
					</div>
					<div class="tab-pane fade" id="history">
						<div class="btn-group margin-top margin-bottom" data-toggle="buttons">
							<label class="btn btn-default" id="dates-all">
								<input type="radio" autocomplete="off">All
							</label>
							<label class="btn btn-default active" id="dates-6m">
								<input type="radio" autocomplete="off" checked>6m
							</label>
							<label class="btn btn-default" id="dates-3m">
								<input type="radio" autocomplete="off">3m
							</label>
							<label class="btn btn-default" id="dates-1m">
								<input type="radio" autocomplete="off">1m
							</label>
						</div>
						<div class="well">
							<canvas id="itemhistory" width="100%"></canvas>
						</div>
						<div class="well">
							<canvas id="tradevolume" width="100%"></canvas>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" href="#collapseOne" aria-expanded="false" class="collapsed">Raw Data</a>
								</h4>
							</div>
							<div id="collapseOne" class="panel-collapse collapse" aria-expanded="false">
								<div class="table-responsive">
									<table id="rawhistory" class="table responsive table-striped table-condensed" width="100%"></table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="panel panel-default browse-panel">
			<div class="panel-body no-padding browse-panel" id="g0b"></div>
		</div>
	</div>
</div>
{% endblock %}
