{% extends "base.phtml" %}
{% block title %}Fortizar Chain{% endblock %}
{% block extrastyle %}
<style type="text/css">
#canvasWrapper {
    border-style: solid;
    width: 800px;
    height: 600px;
}
</style>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3><i class="fa fa-share-alt fa-fw"></i> Fortizar Chain</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div id="canvasWrapper">
			<canvas id="mapCanvas">
			</canvas>
		</div>
	</div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript" src="/js/fortizar-chain.js"></script>
{% endblock %}
