<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		
		<title>DIRT</title>
		
		<!-- Bootstrap Core CSS -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<!-- Custom Fonts -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
		<!-- Custom CSS -->
		<link href="/css/landing-page.css" rel="stylesheet">
		
		<!-- jQuery -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
		<!-- Bootstrap Core JavaScript -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
			<div class="container topnav">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand topnav" href="#">DIRT</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#about">About</a>
						</li>
						<li>
							<a href="#services">Services</a>
						</li>
						<li>
							<a href="#contact">Contact</a>
						</li>
						<li>
							<a href="/login">Login</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<a name="about"></a>
		<div class="intro-header">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="intro-message">
							<h1>DIRT</h1>
							<h3>Market Tools for Eve Online</h3>
							<hr class="intro-divider">
							<ul class="list-inline intro-social-buttons">
								<li>
									<a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
								</li>
								<li>
									<a href="https://github.com/segfault24/dirt" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
								</li>
								<li>
									<a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<a name="services"></a>
		<div class="content-section-a">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-sm-6">
						<hr class="section-heading-spacer">
						<div class="clearfix"></div>
						<h2 class="section-heading">Header 1<br>Header 2</h2>
						<p class="lead">Blah blah blah blah blah.</p>
					</div>
					<div class="col-lg-5 col-lg-offset-2 col-sm-6">
						<img class="img-responsive" src="img/ipad.png" alt="">
					</div>
				</div>
			</div>
		</div>
		<div class="content-section-b">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
						<hr class="section-heading-spacer">
						<div class="clearfix"></div>
						<h2 class="section-heading">somethingsomething</h2>
						<p class="lead">Blah</p>
					</div>
					<div class="col-lg-5 col-sm-pull-6  col-sm-6">
						<img class="img-responsive" src="img/dog.png" alt="">
					</div>
				</div>
			</div>
		</div>
		<div class="content-section-a">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-sm-6">
						<hr class="section-heading-spacer">
						<div class="clearfix"></div>
						<h2 class="section-heading">Powered By</h2>
						<p class="lead">Slim, Bootstrap, SB Admin 2, DataTables, Chart.js</p>
					</div>
					<div class="col-lg-5 col-lg-offset-2 col-sm-6">
						<img class="img-responsive" src="img/phones.png" alt="">
					</div>
				</div>
			</div>
		</div>
		<a name="contact"></a>
		<div class="banner">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<h2>Connect to Start Bootstrap:</h2>
					</div>
					<div class="col-lg-6">
						<ul class="list-inline banner-social-buttons">
							<li>
								<a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
							</li>
							<li>
								<a href="https://github.com/segfault24/dirt" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
							</li>
							<li>
								<a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<footer>
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="list-inline">
							<li>
								<a href="#">Home</a>
							</li>
							<li class="footer-menu-divider">&sdot;</li>
							<li>
								<a href="#about">About</a>
							</li>
							<li class="footer-menu-divider">&sdot;</li>
							<li>
								<a href="#services">Services</a>
							</li>
							<li class="footer-menu-divider">&sdot;</li>
							<li>
								<a href="#contact">Contact</a>
							</li>
						</ul>
						<p class="copyright text-muted small">Copyright &copy; Austin Selick-Bottos 2017. Some Rights Reserved</p>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>
